services:
  ztp-local:
    build: .
    restart: unless-stopped
    image: ztp-flask-local:1.1
    
    ports:
      - "8080:8080"
    volumes:
      - ./scripts/cumulus-ztp-flask.sh:/app/scripts/cumulus-ztp-flask.sh:ro
      - ./images:/app/images:ro
      - ./configs:/app/configs:ro
      - ./logs:/app/logs
